
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Felipe
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final DefaultListModel modeloPartidos;
    private final DefaultListModel modeloResultados;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        modeloPartidos = new DefaultListModel();
        modeloResultados = new DefaultListModel();
        jlPartidos.setModel(modeloPartidos);
        jlResultados.setModel(modeloResultados);

    }
    
    /**
     * Este metodo genera un resultado aleatorio
     * @return resultado del partido
     */
    private char getResultadoPartido() 
    {
        Random aleatorio = new Random();
        int n = aleatorio.nextInt(3);
        char resultado = '\0';
        switch (n)
        {
            case 0:
                resultado = '1';
                break;
            case 1:
                resultado = 'X';
                break;
            case 2:
                resultado = '2';
                break;
        }
        return resultado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorte = new javax.swing.JPanel();
        lQuiniela = new javax.swing.JLabel();
        lPartidos = new javax.swing.JLabel();
        lResultados = new javax.swing.JLabel();
        pCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlPartidos = new javax.swing.JList<>();
        pCCentro = new javax.swing.JPanel();
        pBotones = new javax.swing.JPanel();
        bNuevo = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bRealizar = new javax.swing.JButton();
        bResetear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlResultados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pNorte.setLayout(new java.awt.BorderLayout());

        lQuiniela.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 30)); // NOI18N
        lQuiniela.setForeground(new java.awt.Color(255, 0, 0));
        lQuiniela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lQuiniela.setText("Quiniela");
        pNorte.add(lQuiniela, java.awt.BorderLayout.NORTH);

        lPartidos.setText("Partidos");
        pNorte.add(lPartidos, java.awt.BorderLayout.WEST);

        lResultados.setText("Resultados");
        pNorte.add(lResultados, java.awt.BorderLayout.EAST);

        getContentPane().add(pNorte, java.awt.BorderLayout.PAGE_START);

        pCentro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pCentro.setLayout(new java.awt.GridLayout());

        jlPartidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "asdfasdf", "asdfasdf", "asdfsdf" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlPartidos);

        pCentro.add(jScrollPane1);

        pBotones.setLayout(new java.awt.GridLayout(4, 1));

        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });
        pBotones.add(bNuevo);

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        pBotones.add(bEliminar);

        bRealizar.setText("Realizar quiniela");
        bRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizarActionPerformed(evt);
            }
        });
        pBotones.add(bRealizar);

        bResetear.setText("Resetear");
        bResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetearActionPerformed(evt);
            }
        });
        pBotones.add(bResetear);

        pCCentro.add(pBotones);

        pCentro.add(pCCentro);

        jlResultados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "asdfasdf", "asdfasdf" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlResultados);

        pCentro.add(jScrollPane2);

        getContentPane().add(pCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * El botón Nuevo sirve para añadir un partido
     * @param evt abre una ventana nueva y añade un partido
     */
    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        final String respuesta = (String) JOptionPane.showInputDialog(
                this,
                "Partido",
                "Agregar un partido",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null,
                null);

        modeloPartidos.addElement(respuesta);
    }//GEN-LAST:event_bNuevoActionPerformed

    /**
     * El botón Eliminar sirve para eliminar un partido de la lista Partidos
     * @param evt elimina un partido de la lista partidos
     */
    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        int elemento = jlPartidos.getSelectedIndex();
        if (elemento >= 0) 
            modeloPartidos.remove(elemento);
        else 
        {
            JOptionPane.showMessageDialog(this, "No hay elementos seleccionados.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    /**
     * El botón Realizar quiniela rellena la quieniela en la lista Resultados
     * @param evt rellena la quiniela en la lista resultados
     */
    private void bRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarActionPerformed
        // Limpiamos si hay resultados existentes
        modeloResultados.clear();
        // Calculamos nuevos resultados
        for (int i = 0; i < modeloPartidos.size(); i++) 
        {
            String elementoPartido = ((String) modeloPartidos.get(i)) + " -> " + getResultadoPartido();
            modeloResultados.addElement(elementoPartido);
        }
    }//GEN-LAST:event_bRealizarActionPerformed

    /**
     * El botón Resetear limpia las dos listas
     * @param evt limpia las dos listas
     */
    private void bResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetearActionPerformed
        modeloPartidos.clear();
        modeloResultados.clear();
    }//GEN-LAST:event_bResetearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bRealizar;
    private javax.swing.JButton bResetear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlPartidos;
    private javax.swing.JList<String> jlResultados;
    private javax.swing.JLabel lPartidos;
    private javax.swing.JLabel lQuiniela;
    private javax.swing.JLabel lResultados;
    private javax.swing.JPanel pBotones;
    private javax.swing.JPanel pCCentro;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorte;
    // End of variables declaration//GEN-END:variables
}
